# Generated by Django 6.1 on 2026-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking', 'Booking Notification'), ('payment', 'Payment Notification'), ('approval', 'Event Approval'), ('cancellation', 'Cancellation Notice'), ('reminder', 'Event Reminder'), ('system', 'System Message')], default='system', max_length=30)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
