from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import timedelta, date, time
from decimal import Decimal
from apps.users.models import User, UserRole
from apps.events.models import Category, Event, EventStatus, EventType, Speaker, EventSchedule, TicketType

class Command(BaseCommand):
    help = 'Seeds at least 15 rich events with 100% unique photos for Conferences, Food & Drinks, Networking, and Cultural & Arts.'

    def handle(self, *args, **options):
        self.stdout.write("Starting comprehensive seeding for the 4 additional categories...")

        # Organizers
        org_conf, _ = User.objects.get_or_create(
            email='conferences.org@eventsphere.com',
            defaults={
                'username': 'globalsummits_org',
                'first_name': 'Dr. Vikramaditya',
                'last_name': 'Sen',
                'role': UserRole.ORGANIZER,
                'organization_name': 'Global Summits & Conventions Council',
                'organization_description': 'Organizing premier international conferences, keynotes and mega-conventions.',
                'website': 'https://globalsummits.org',
                'is_verified_organizer': True,
                'avatar_url': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
            }
        )
        org_food, _ = User.objects.get_or_create(
            email='food.org@eventsphere.com',
            defaults={
                'username': 'culinaryarts_org',
                'first_name': 'Chef Sanjeev',
                'last_name': 'Kapoor',
                'role': UserRole.ORGANIZER,
                'organization_name': 'Gourmet Guild & Food Festivals',
                'organization_description': 'Curating extraordinary culinary expos, craft brewery fests and fine dining masterclasses.',
                'website': 'https://gourmetguild.in',
                'is_verified_organizer': True,
                'avatar_url': 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=200&auto=format&fit=crop&q=80',
            }
        )
        org_net, _ = User.objects.get_or_create(
            email='networking.org@eventsphere.com',
            defaults={
                'username': 'connecthub_org',
                'first_name': 'Natasha',
                'last_name': 'Verma',
                'role': UserRole.ORGANIZER,
                'organization_name': 'Executive Connect & Networking Lounge',
                'organization_description': 'Facilitating high-value business networking, angel syndicates and speed matchmaking.',
                'website': 'https://connecthub.events',
                'is_verified_organizer': True,
                'avatar_url': 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
            }
        )
        org_arts, _ = User.objects.get_or_create(
            email='arts.org@eventsphere.com',
            defaults={
                'username': 'heritagearts_org',
                'first_name': 'Meenakshi',
                'last_name': 'Sundaram',
                'role': UserRole.ORGANIZER,
                'organization_name': 'Heritage & Fine Arts Foundation',
                'organization_description': 'Preserving and promoting traditional dance, theatre, classical arts and literature festivals.',
                'website': 'https://heritagearts.org',
                'is_verified_organizer': True,
                'avatar_url': 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
            }
        )

        # Categories
        cat_conf, _ = Category.objects.update_or_create(
            slug='conferences',
            defaults={
                'name': 'Conferences',
                'icon': 'Users',
                'description': 'Keynotes, Panel Discussions & Industry Mega-Conventions',
                'image_url': 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
                'is_popular': True,
                'order': 7
            }
        )
        cat_food, _ = Category.objects.update_or_create(
            slug='food-drinks',
            defaults={
                'name': 'Food & Drinks',
                'icon': 'Utensils',
                'description': 'Culinary Festivals, Craft Beer Tasting & Gourmet Pop-ups',
                'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80',
                'is_popular': True,
                'order': 8
            }
        )
        cat_net, _ = Category.objects.update_or_create(
            slug='networking',
            defaults={
                'name': 'Networking',
                'icon': 'Network',
                'description': 'Executive Mixers, Speed Mentoring & Community Meetups',
                'image_url': 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&auto=format&fit=crop&q=80',
                'is_popular': True,
                'order': 9
            }
        )
        cat_arts, _ = Category.objects.update_or_create(
            slug='cultural',
            defaults={
                'name': 'Cultural & Arts',
                'icon': 'Sparkles',
                'description': 'Heritage Shows, Theatre, Poetry Slams & Art Exhibitions',
                'image_url': 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&auto=format&fit=crop&q=80',
                'is_popular': True,
                'order': 10
            }
        )

        # -------------------------------------------------------------
        # 1. CONFERENCES (15 Events)
        # -------------------------------------------------------------
        conf_events = [
            {
                'title': 'Global Healthcare & Medical Leadership Summit 2026',
                'slug': 'global-healthcare-medical-leadership-summit',
                'short_description': 'Digital health systems, precision oncology, hospital operations, and healthcare robotics.',
                'description': 'Gathering 2,500+ hospital directors, senior surgeons, and biotechnology innovators to discuss modern medical breakthroughs.',
                'banner_image_url': 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.HYBRID,
                'venue_name': 'Bharat Mandapam Convention Hall 1',
                'city': 'New Delhi',
                'days_ahead': 25,
                'is_featured': True,
                'tickets': [{'name': 'Delegate Pass', 'price': Decimal('2499.00'), 'total_quantity': 250}],
            },
            {
                'title': 'International Climate Action & Sustainability Convention',
                'slug': 'climate-action-sustainability-convention',
                'short_description': 'Carbon capture tech, ESG governance, zero-waste supply chains, and green infrastructure.',
                'description': 'Global leaders, environmental scientists, and policymakers establish actionable goals for industrial decarbonization.',
                'banner_image_url': 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'India Habitat Centre Stein Auditorium',
                'city': 'New Delhi',
                'days_ahead': 33,
                'is_featured': False,
                'tickets': [{'name': 'General Pass', 'price': Decimal('1499.00'), 'total_quantity': 200}],
            },
            {
                'title': 'World Higher Education & University Leadership Conclave',
                'slug': 'higher-education-university-leadership-conclave',
                'short_description': 'AI in curriculum design, research commercialization, global student mobility, and campus tech.',
                'description': 'Vice Chancellors, deans, and education technology leaders debate the future of universities in the age of intelligence.',
                'banner_image_url': 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Taj West End Ballroom',
                'city': 'Bengaluru',
                'days_ahead': 29,
                'is_featured': False,
                'tickets': [{'name': 'Academic Leader Pass', 'price': Decimal('1999.00'), 'total_quantity': 150}],
            },
            {
                'title': 'Aviation, Drones & Aerospace Future Summit 2026',
                'slug': 'aviation-drones-aerospace-future-summit',
                'short_description': 'Commercial eVTOL aircraft, autonomous drone corridors, and satellite launch networks.',
                'description': 'Pilots, aerospace engineers, defense contractors, and airline executives present cutting-edge flight innovations.',
                'banner_image_url': 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Yelahanka Air Base Exhibition Arena',
                'city': 'Bengaluru',
                'days_ahead': 45,
                'is_featured': False,
                'tickets': [{'name': 'Aerospace Pass', 'price': Decimal('2999.00'), 'total_quantity': 180}],
            },
            {
                'title': 'Global Supply Chain & Multimodal Logistics Congress',
                'slug': 'supply-chain-multimodal-logistics-congress',
                'short_description': 'Automated warehousing, freight digitization, cold-chain tracking, and port terminal robotics.',
                'description': 'Logistics directors and cargo operators optimize freight routes and implement automated material handling.',
                'banner_image_url': 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Jio World Convention Centre Hall 2',
                'city': 'Mumbai',
                'days_ahead': 38,
                'is_featured': False,
                'tickets': [{'name': 'Supply Chain Pass', 'price': Decimal('1899.00'), 'total_quantity': 200}],
            },
            {
                'title': 'Renewable Hydrogen & Clean Energy Mega-Conference',
                'slug': 'renewable-hydrogen-clean-energy-conference',
                'short_description': 'Green hydrogen electrolyzers, fuel-cell logistics, and mega-watt solar grid integration.',
                'description': 'Energy ministers and power utility CEOs evaluate gigawatt-scale renewable production and storage systems.',
                'banner_image_url': 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Gujarat International Finance Tec-City (GIFT City)',
                'city': 'Gandhinagar',
                'days_ahead': 41,
                'is_featured': False,
                'tickets': [{'name': 'Energy Pass', 'price': Decimal('2199.00'), 'total_quantity': 160}],
            },
            {
                'title': 'Cyber Law, Data Privacy & AI Intellectual Property Forum',
                'slug': 'cyber-law-privacy-ai-ip-forum',
                'short_description': 'Navigating global DPDP acts, EU AI regulation, algorithmic copyright, and corporate compliance.',
                'description': 'Senior Supreme Court advocates, general counsels, and compliance heads debate algorithmic liabilities and data governance.',
                'banner_image_url': 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'The Claridges Convention Hall',
                'city': 'New Delhi',
                'days_ahead': 21,
                'is_featured': False,
                'tickets': [{'name': 'Legal Pass', 'price': Decimal('1799.00'), 'total_quantity': 140}],
            },
            {
                'title': 'Smart Cities, Urban Mobility & Infrastructure Summit',
                'slug': 'smart-cities-urban-mobility-infrastructure-summit',
                'short_description': 'Intelligent traffic management, metro rail automation, EV charging grids, and smart civic sensors.',
                'description': 'Urban planners and civil engineering leaders shape sustainable, connected cities of the next generation.',
                'banner_image_url': 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Hyderabad International Trade Expositions (HITEX)',
                'city': 'Hyderabad',
                'days_ahead': 35,
                'is_featured': False,
                'tickets': [{'name': 'Urban Planner Pass', 'price': Decimal('1599.00'), 'total_quantity': 180}],
            },
            {
                'title': 'Global Wealth Management & Family Office Convention',
                'slug': 'wealth-management-family-office-convention',
                'short_description': 'Private equity allocation, multi-generational wealth succession, and alternative asset portfolios.',
                'description': 'An exclusive gathering for single-family offices, ultra-HNIs, and private bankers managing $100M+ portfolios.',
                'banner_image_url': 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'The Oberoi Grand Ballroom',
                'city': 'Mumbai',
                'days_ahead': 48,
                'is_featured': False,
                'tickets': [{'name': 'Family Office Delegate', 'price': Decimal('4999.00'), 'total_quantity': 80}],
            },
            {
                'title': 'International Real Estate & PropTech Investment Expo',
                'slug': 'international-real-estate-proptech-expo',
                'short_description': 'Commercial REITs, luxury real estate, smart building IoT, and fractional property tokens.',
                'description': 'Connecting major property developers, commercial funds, and proptech software builders.',
                'banner_image_url': 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Bombay Exhibition Centre Hall 1',
                'city': 'Mumbai',
                'days_ahead': 26,
                'is_featured': False,
                'tickets': [{'name': 'Real Estate Pass', 'price': Decimal('1299.00'), 'total_quantity': 300}],
            },
            {
                'title': 'Pharma Manufacturing, Quality & Regulatory Summit',
                'slug': 'pharma-manufacturing-quality-regulatory-summit',
                'short_description': 'US FDA compliance, continuous sterile manufacturing, biosimilar validation, and cleanroom tech.',
                'description': 'Plant heads, QA directors, and pharmaceutical scientists discuss global pharmacopeia standards.',
                'banner_image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Novotel Hyderabad Convention Centre',
                'city': 'Hyderabad',
                'days_ahead': 31,
                'is_featured': False,
                'tickets': [{'name': 'Pharma Delegate', 'price': Decimal('2299.00'), 'total_quantity': 180}],
            },
            {
                'title': 'Media, Streaming OTT & Entertainment Leaders Forum',
                'slug': 'media-streaming-ott-entertainment-forum',
                'short_description': 'Content monetization, AI dubbing & translation, CTV advertising, and digital studio pipelines.',
                'description': 'Studio heads, streaming platform VPs, and production pioneers define the future of cinema and OTT broadcasting.',
                'banner_image_url': 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'JW Marriott Sahar',
                'city': 'Mumbai',
                'days_ahead': 20,
                'is_featured': False,
                'tickets': [{'name': 'Media Leader Pass', 'price': Decimal('1999.00'), 'total_quantity': 220}],
            },
            {
                'title': 'Maritime, Sea Ports & Ocean Logistics Convention',
                'slug': 'maritime-sea-ports-ocean-logistics-convention',
                'short_description': 'Green shipping corridors, smart container ports, maritime safety, and automated customs.',
                'description': 'Port authorities, shipping lines, and maritime captains streamline global ocean trade routes.',
                'banner_image_url': 'https://images.unsplash.com/photo-1505705694340-019e1e335916?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Chennai Trade Centre',
                'city': 'Chennai',
                'days_ahead': 52,
                'is_featured': False,
                'tickets': [{'name': 'Maritime Pass', 'price': Decimal('1699.00'), 'total_quantity': 150}],
            },
            {
                'title': 'Autonomous Vehicles & EV Mobility World Congress',
                'slug': 'autonomous-vehicles-ev-mobility-congress',
                'short_description': 'Lidar sensor fusion, solid-state battery tech, charging networks, and DriveOS architecture.',
                'description': 'Automotive OEMs and self-driving software engineers demonstrate autonomous driving platforms.',
                'banner_image_url': 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Auto Cluster Exhibition Center',
                'city': 'Pune',
                'days_ahead': 36,
                'is_featured': False,
                'tickets': [{'name': 'Automotive Pass', 'price': Decimal('2499.00'), 'total_quantity': 200}],
            },
            {
                'title': 'World Nanotechnology & Advanced Materials Forum',
                'slug': 'world-nanotechnology-advanced-materials-forum',
                'short_description': 'Graphene composites, carbon nanotubes, superconductor research, and aerospace metallurgy.',
                'description': 'Materials scientists and nanotechnology researchers present breakthrough molecular engineering discoveries.',
                'banner_image_url': 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.HYBRID,
                'venue_name': 'IISc Faculty Hall',
                'city': 'Bengaluru',
                'days_ahead': 44,
                'is_featured': False,
                'tickets': [{'name': 'Researcher Pass', 'price': Decimal('1399.00'), 'total_quantity': 180}],
            },
        ]

        # -------------------------------------------------------------
        # 2. FOOD & DRINKS (15 Events)
        # -------------------------------------------------------------
        food_events = [
            {
                'title': 'Craft Beer & Artisanal Brewery Carnival 2026',
                'slug': 'craft-beer-artisanal-brewery-carnival',
                'short_description': 'Over 40 microbreweries, IPA tastings, German bratwurst, and live acoustic indie bands.',
                'description': 'Sample the finest handcrafted ales, ciders, and stouts with live brewing masterclasses and gourmet food trucks.',
                'banner_image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'The Royal Palms Turf Club Grounds',
                'city': 'Pune',
                'days_ahead': 17,
                'is_featured': True,
                'tickets': [{'name': 'Tasting Pass (Includes 4 Brews)', 'price': Decimal('699.00'), 'total_quantity': 400}],
            },
            {
                'title': 'Gourmet Coffee Roasters & Barista Championship',
                'slug': 'gourmet-coffee-roasters-barista-championship',
                'short_description': 'Specialty Arabica roasts, pour-over techniques, latte art showdowns, and espresso masterclasses.',
                'description': 'Experience the finest estate-grown coffees from Chikmagalur and Coorg brewed by championship baristas.',
                'banner_image_url': 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Jayanthi Arts & Coffee Pavilion',
                'city': 'Bengaluru',
                'days_ahead': 14,
                'is_featured': False,
                'tickets': [{'name': 'Coffee Lover Pass', 'price': Decimal('499.00'), 'total_quantity': 350}],
            },
            {
                'title': 'Wine Tasting & Vineyard Harvest Sunset Gala',
                'slug': 'wine-tasting-vineyard-harvest-sunset-gala',
                'short_description': 'Grape stomping, vintage reserve wines, cheese pairings, and jazz music in the vineyards.',
                'description': 'A romantic weekend retreat in the lush Nashik wine valley with private barrel tastings and sunset dinners.',
                'banner_image_url': 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Sula Vineyard Open Amphitheatre',
                'city': 'Nashik',
                'days_ahead': 24,
                'is_featured': False,
                'tickets': [{'name': 'Wine & Dine Pass', 'price': Decimal('1899.00'), 'total_quantity': 150}],
            },
            {
                'title': 'Street Food of India Mega Fiesta 2026',
                'slug': 'street-food-india-mega-fiesta-2026',
                'short_description': 'Over 200 authentic regional delicacies from Lucknowi kebabs to Kolkata kathi rolls and Dilli chaat.',
                'description': 'The ultimate gastronomic journey across 28 states with live folk entertainment and dessert corners.',
                'banner_image_url': 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'JLN Stadium Food Village',
                'city': 'New Delhi',
                'days_ahead': 28,
                'is_featured': True,
                'tickets': [{'name': 'Entry Pass + Food Voucher', 'price': Decimal('399.00'), 'total_quantity': 600}],
            },
            {
                'title': 'Chocolate, Pastry & Dessert Artistry Expo',
                'slug': 'chocolate-pastry-dessert-artistry-expo',
                'short_description': 'Single-origin dark chocolates, French macarons, chocolate sculptures, and pastry masterclasses.',
                'description': 'Master chocolatiers and celebrity pastry chefs demonstrate tempering, sugar pulling, and gourmet truffles.',
                'banner_image_url': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'World Trade Center Grand Ballroom',
                'city': 'Mumbai',
                'days_ahead': 19,
                'is_featured': False,
                'tickets': [{'name': 'Sweet Tooth Pass', 'price': Decimal('599.00'), 'total_quantity': 300}],
            },
            {
                'title': 'Vegan, Plant-Based & Organic Food Festival',
                'slug': 'vegan-plant-based-organic-food-festival',
                'short_description': 'Dairy-free cheeses, meat-free gourmet burgers, cold-pressed juices, and cruelty-free lifestyle.',
                'description': 'Discover delicious plant-powered dining, superfoods, and holistic wellness nutrition with zero compromise on taste.',
                'banner_image_url': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Palace Grounds Gayatri Vihar',
                'city': 'Bengaluru',
                'days_ahead': 22,
                'is_featured': False,
                'tickets': [{'name': 'Eco Food Pass', 'price': Decimal('449.00'), 'total_quantity': 400}],
            },
            {
                'title': 'Mixology, Cocktails & Craft Gin Showcase',
                'slug': 'mixology-cocktails-craft-gin-showcase',
                'short_description': 'Botanical gin infusions, smoky mezcals, flair bartending showdowns, and live house DJs.',
                'description': 'Top international mixologists craft signature cocktails with artisanal tonics and indigenous botanicals.',
                'banner_image_url': 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Olive Bar & Kitchen Courtyard',
                'city': 'Goa',
                'days_ahead': 31,
                'is_featured': False,
                'tickets': [{'name': 'Cocktail Tasting Pass', 'price': Decimal('999.00'), 'total_quantity': 250}],
            },
            {
                'title': 'MasterChef Live Cooking & 7-Course Fine Dining',
                'slug': 'masterchef-live-cooking-fine-dining',
                'short_description': 'Watch Michelin-starred chefs plate culinary masterpieces live before tasting their 7-course menu.',
                'description': 'An unforgettable evening of molecular gastronomy, paired wines, and chef storytelling in an intimate dining suite.',
                'banner_image_url': 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'The St. Regis Dining Hall',
                'city': 'Mumbai',
                'days_ahead': 27,
                'is_featured': False,
                'tickets': [{'name': 'Gourmet Table Seat', 'price': Decimal('3499.00'), 'total_quantity': 60}],
            },
            {
                'title': 'Artisanal Cheese, Sourdough & Charcuterie Atelier',
                'slug': 'artisanal-cheese-sourdough-charcuterie-atelier',
                'short_description': 'Handcrafted gouda, brie, truffle honey, naturally leavened sourdough, and board styling.',
                'description': 'Learn cheese aging and pair bespoke fromages with artisanal sourdough breads and fig preserves.',
                'banner_image_url': 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'The Conservatory Hall',
                'city': 'Bengaluru',
                'days_ahead': 16,
                'is_featured': False,
                'tickets': [{'name': 'Cheese Board Pass', 'price': Decimal('899.00'), 'total_quantity': 100}],
            },
            {
                'title': 'BBQ, Smoked Meats & Fire Cooking Cookoff',
                'slug': 'bbq-smoked-meats-fire-cooking-cookoff',
                'short_description': 'Low-and-slow Texas style brisket, wood-fired skewers, pitmasters, and spicy BBQ glazes.',
                'description': 'The smoky aroma of wood-fired grills and competition BBQ pitmasters battling for the Golden Skewer trophy.',
                'banner_image_url': 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Bavdhan Open BBQ Grounds',
                'city': 'Pune',
                'days_ahead': 34,
                'is_featured': False,
                'tickets': [{'name': 'Carnivore Feast Pass', 'price': Decimal('1199.00'), 'total_quantity': 250}],
            },
            {
                'title': 'Asian Hawker & Dim Sum Street Fair',
                'slug': 'asian-hawker-dim-sum-street-fair',
                'short_description': 'Steaming bao buns, crystal dumplings, fiery ramen, boba teas, and night market lantern vibes.',
                'description': 'Immerse in Tokyo, Bangkok, and Hong Kong night market street food stalls with live wok tossing action.',
                'banner_image_url': 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Cyber Hub Open Courtyard',
                'city': 'Gurugram',
                'days_ahead': 23,
                'is_featured': False,
                'tickets': [{'name': 'Night Market Pass', 'price': Decimal('499.00'), 'total_quantity': 450}],
            },
            {
                'title': 'Farm-to-Table Organic Harvest Sunset Dinner',
                'slug': 'farm-to-table-organic-harvest-sunset-dinner',
                'short_description': 'Dine directly in the fields under twinkling fairy lights with 100% locally harvested organic ingredients.',
                'description': 'Tour the organic permaculture farm before sitting down to an al fresco multi-course rustic feast with live cello music.',
                'banner_image_url': 'https://images.unsplash.com/photo-1505935428862-770b6f24f629?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Vriddhishree Eco Farm',
                'city': 'Hyderabad',
                'days_ahead': 29,
                'is_featured': False,
                'tickets': [{'name': 'Farm Dinner Seat', 'price': Decimal('1599.00'), 'total_quantity': 80}],
            },
            {
                'title': 'Artisanal Bakery, Croissant & Sourdough Expo',
                'slug': 'artisanal-bakery-croissant-sourdough-expo',
                'short_description': 'Laminated French croissants, pain au chocolat, sourdough boules, and professional baking ovens.',
                'description': 'Master bakers reveal the secrets of wild yeast fermentation, dough folding, and golden flaky crusts.',
                'banner_image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'NESCO Exhibition Center Hall 3',
                'city': 'Mumbai',
                'days_ahead': 37,
                'is_featured': False,
                'tickets': [{'name': 'Baker Pass', 'price': Decimal('549.00'), 'total_quantity': 280}],
            },
            {
                'title': 'Tea Masters & Himalayan Chai Conclave',
                'slug': 'tea-masters-himalayan-chai-conclave',
                'short_description': 'First flush Darjeeling, matcha whisking, Kashmiri kahwa, and single-estate tea tastings.',
                'description': 'Tea sommeliers guide mindful tea ceremonies and explore the health benefits of rare Himalayan botanicals.',
                'banner_image_url': 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Victoria Memorial Tea Pavilion',
                'city': 'Kolkata',
                'days_ahead': 42,
                'is_featured': False,
                'tickets': [{'name': 'Tea Connoisseur Pass', 'price': Decimal('499.00'), 'total_quantity': 200}],
            },
            {
                'title': 'Seafood & Coastal Flavours Festival 2026',
                'slug': 'seafood-coastal-flavours-festival',
                'short_description': 'Fresh crab masala, butter garlic prawns, Goan fish curry, and live acoustic Konkani music.',
                'description': 'Celebrate rich coastal culinary traditions from Malabar, Konkan, and Bengal right on the breezy seaside.',
                'banner_image_url': 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Baga Beach Coastal Arena',
                'city': 'Goa',
                'days_ahead': 46,
                'is_featured': False,
                'tickets': [{'name': 'Seafood Feast Pass', 'price': Decimal('899.00'), 'total_quantity': 300}],
            },
        ]

        # -------------------------------------------------------------
        # 3. NETWORKING (15 Events)
        # -------------------------------------------------------------
        net_events = [
            {
                'title': 'Tech Founders & Angel Investors Speed Matchmaking',
                'slug': 'tech-founders-angel-investors-speed-matchmaking',
                'short_description': 'Fast-paced 10-minute curated 1-on-1 pitch slots connecting seed startups with accredited angels.',
                'description': 'Over 30 verified angel investors meeting 60 curated tech founders looking to close their seed rounds.',
                'banner_image_url': 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'T-Hub Rooftop Lounge',
                'city': 'Hyderabad',
                'days_ahead': 15,
                'is_featured': True,
                'tickets': [{'name': 'Founder Pitch Slot', 'price': Decimal('1999.00'), 'total_quantity': 60}],
            },
            {
                'title': 'C-Suite & Executive Rooftop Networking Mixer',
                'slug': 'csuite-executive-rooftop-networking-mixer',
                'short_description': 'High-level evening with CEOs, CTOs, and Managing Directors over handcrafted cocktails.',
                'description': 'Unwind and discuss enterprise strategy, acquisitions, and boardroom perspectives with industry peers.',
                'banner_image_url': 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Four Seasons Aer Rooftop Lounge',
                'city': 'Mumbai',
                'days_ahead': 18,
                'is_featured': False,
                'tickets': [{'name': 'Executive Invitation', 'price': Decimal('2999.00'), 'total_quantity': 50}],
            },
            {
                'title': 'Creative Directors & Agency Leaders Evening',
                'slug': 'creative-directors-agency-leaders-evening',
                'short_description': 'Advertising heads, design studio founders, and film producers sharing agency growth playbooks.',
                'description': 'An inspiring mixer exploring client pitching, award-winning campaigns, and creative talent retention.',
                'banner_image_url': 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Social Space Church Street',
                'city': 'Bengaluru',
                'days_ahead': 21,
                'is_featured': False,
                'tickets': [{'name': 'Agency Pass', 'price': Decimal('1299.00'), 'total_quantity': 80}],
            },
            {
                'title': 'Young Professionals & Startup Connect Lounge',
                'slug': 'young-professionals-startup-connect-lounge',
                'short_description': 'Connect with ambitious developers, product managers, and growth hackers in a vibrant setting.',
                'description': 'Expand your professional network, find co-founders, and explore exciting job openings at rocketship startups.',
                'banner_image_url': 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'WeWork Two Horizon Center',
                'city': 'Gurugram',
                'days_ahead': 12,
                'is_featured': False,
                'tickets': [{'name': 'Social Pass', 'price': Decimal('499.00'), 'total_quantity': 150}],
            },
            {
                'title': 'Freelancers, Solo-Founders & Remote Workers Meetup',
                'slug': 'freelancers-solofounders-remote-workers-meetup',
                'short_description': 'Co-working session, client acquisition tips, high-ticket pricing strategies, and casual coffee.',
                'description': 'Meet fellow remote digital nomads and indie hackers to share productivity workflows and swap client referrals.',
                'banner_image_url': 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Third Wave Coffee Roasters Koramangala',
                'city': 'Bengaluru',
                'days_ahead': 10,
                'is_featured': False,
                'tickets': [{'name': 'Meetup Pass (Coffee Included)', 'price': Decimal('349.00'), 'total_quantity': 75}],
            },
            {
                'title': 'Alumni Leaders & Ivy League Networking Gala',
                'slug': 'alumni-leaders-ivy-league-networking-gala',
                'short_description': 'Graduates from premier global universities gather for an evening of fireside chats and cocktails.',
                'description': 'Re-connect with alumni from top technology and business institutes across finance, consulting, and tech.',
                'banner_image_url': 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'The Leela Palace Grand Ballroom',
                'city': 'Bengaluru',
                'days_ahead': 32,
                'is_featured': False,
                'tickets': [{'name': 'Alumni Pass', 'price': Decimal('2199.00'), 'total_quantity': 100}],
            },
            {
                'title': 'Global Expats & Digital Nomads Social Mixer',
                'slug': 'global-expats-digital-nomads-social-mixer',
                'short_description': 'International residents, tech expats, and traveling creators sharing cultural experiences in Goa.',
                'description': 'Live acoustic music, international bar snacks, and travel tips on living and working in tropical destinations.',
                'banner_image_url': 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Anjuna Garden Club',
                'city': 'Goa',
                'days_ahead': 26,
                'is_featured': False,
                'tickets': [{'name': 'Expat Pass', 'price': Decimal('599.00'), 'total_quantity': 120}],
            },
            {
                'title': 'Women in Leadership & VC Networking Dinner',
                'slug': 'women-leadership-vc-networking-dinner',
                'short_description': 'An empowering dinner for female founders, venture partners, and executive directors.',
                'description': 'Building strong allyship, sharing board governance opportunities, and unlocking early-stage venture funding.',
                'banner_image_url': 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'ITC Grand Central Rooftop',
                'city': 'Mumbai',
                'days_ahead': 24,
                'is_featured': True,
                'tickets': [{'name': 'Dinner Seat', 'price': Decimal('1999.00'), 'total_quantity': 60}],
            },
            {
                'title': 'Product Leaders & Tech Architects Roundtable',
                'slug': 'product-leaders-tech-architects-roundtable',
                'short_description': 'Principal Engineers and Heads of Product discussing system scale, tech debt, and AI integration.',
                'description': 'Closed-door candid discussions with engineering VPs on building systems that handle billions of daily requests.',
                'banner_image_url': 'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Microsoft Innovation Lounge',
                'city': 'Bengaluru',
                'days_ahead': 28,
                'is_featured': False,
                'tickets': [{'name': 'Roundtable Pass', 'price': Decimal('1499.00'), 'total_quantity': 45}],
            },
            {
                'title': 'Real Estate & Private Equity Syndicate Mixer',
                'slug': 'real-estate-private-equity-syndicate-mixer',
                'short_description': 'Connecting commercial property developers with private equity syndicates and family funds.',
                'description': 'Structured discussions on debt structuring, land acquisition financing, and commercial rental yields.',
                'banner_image_url': 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Grand Hyatt Executive Room',
                'city': 'Mumbai',
                'days_ahead': 35,
                'is_featured': False,
                'tickets': [{'name': 'Investor Pass', 'price': Decimal('3499.00'), 'total_quantity': 50}],
            },
            {
                'title': 'Startup Founders Breakfast & Mastermind Club',
                'slug': 'startup-founders-breakfast-mastermind-club',
                'short_description': 'Monthly morning mastermind solving hiring bottlenecks, product roadmap delays, and burn rate.',
                'description': 'A supportive group of 15 seed to Series-A founders giving honest feedback over gourmet breakfast.',
                'banner_image_url': 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Smoke House Deli Indiranagar',
                'city': 'Bengaluru',
                'days_ahead': 9,
                'is_featured': False,
                'tickets': [{'name': 'Founder Breakfast Pass', 'price': Decimal('799.00'), 'total_quantity': 30}],
            },
            {
                'title': 'Growth Marketers & Performance Ad Social Mixer',
                'slug': 'growth-marketers-performance-ad-social',
                'short_description': 'Meta ad algorithms, TikTok/Reels organic virality, and CAC optimization over craft beer.',
                'description': 'Media buyers spending $50k+/month share real data on conversion rate optimization and creative testing.',
                'banner_image_url': 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Toit Brewpub Indiranagar',
                'city': 'Bengaluru',
                'days_ahead': 16,
                'is_featured': False,
                'tickets': [{'name': 'Marketer Pass', 'price': Decimal('699.00'), 'total_quantity': 90}],
            },
            {
                'title': 'Software Engineers & Open Source Community Meetup',
                'slug': 'software-engineers-open-source-community-meetup',
                'short_description': 'Lightning talks on Rust, Go, Linux kernel modules, and contributing to high-impact open source.',
                'description': 'Hang out with maintainers of popular GitHub repositories, grab pizza, and hack on community projects.',
                'banner_image_url': 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'DevHub Co-working space',
                'city': 'Pune',
                'days_ahead': 14,
                'is_featured': False,
                'tickets': [{'name': 'Free Community RSVP', 'price': Decimal('0.00'), 'total_quantity': 150}],
            },
            {
                'title': 'Healthcare Leaders & Doctors Business Forum',
                'slug': 'healthcare-leaders-doctors-business-forum',
                'short_description': 'Clinical practice expansion, hospital accreditation, and healthtech partnerships.',
                'description': 'Doctors, clinic owners, and medical diagnostic entrepreneurs network to build integrated healthcare networks.',
                'banner_image_url': 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Apollo Knowledge Center',
                'city': 'Chennai',
                'days_ahead': 39,
                'is_featured': False,
                'tickets': [{'name': 'Doctor Pass', 'price': Decimal('1199.00'), 'total_quantity': 100}],
            },
            {
                'title': 'Creative Artists & Illustrators Portfolio Mixer',
                'slug': 'creative-artists-illustrators-portfolio-mixer',
                'short_description': 'Showcase your sketchbook, meet art buyers, commission clients, and indie publishers.',
                'description': 'Bring your physical or iPad art portfolio to connect with art directors and get commissioned for brand projects.',
                'banner_image_url': 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Artisans Gallery Kala Ghoda',
                'city': 'Mumbai',
                'days_ahead': 22,
                'is_featured': False,
                'tickets': [{'name': 'Artist RSVP', 'price': Decimal('399.00'), 'total_quantity': 120}],
            },
        ]

        # -------------------------------------------------------------
        # 4. CULTURAL & ARTS (15 Events)
        # -------------------------------------------------------------
        arts_events = [
            {
                'title': 'Jaipur Literature & Heritage Storytelling Festival 2026',
                'slug': 'jaipur-literature-heritage-storytelling-festival',
                'short_description': 'Book launches, Nobel laureate talks, poetry pavilions, and heritage palace discussions.',
                'description': 'The greatest literary show on Earth bringing together global novelists, historians, and thinkers under colorful royal tents.',
                'banner_image_url': 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Diggi Palace Heritage Grounds',
                'city': 'Jaipur',
                'days_ahead': 30,
                'is_featured': True,
                'tickets': [{'name': 'Festival Delegate Pass', 'price': Decimal('799.00'), 'total_quantity': 500}],
            },
            {
                'title': 'Kathakali, Bharatanatyam & Classical Dance Gala',
                'slug': 'kathakali-bharatanatyam-classical-dance-gala',
                'short_description': 'Exquisite mudras, classical footwork, vibrant traditional costumes, and live percussion.',
                'description': 'A breathtaking celebration of ancient Indian temple dance traditions featuring Padma awardee danseuses.',
                'banner_image_url': 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Kalakshetra Foundation Auditorium',
                'city': 'Chennai',
                'days_ahead': 21,
                'is_featured': False,
                'tickets': [{'name': 'Auditorium Seat', 'price': Decimal('699.00'), 'total_quantity': 350}],
            },
            {
                'title': 'Contemporary Art Biennale & Open Gallery Walk',
                'slug': 'contemporary-art-biennale-open-gallery-walk',
                'short_description': 'Immersive 3D art installations, modern sculptures, video art projections, and artist talks.',
                'description': 'Explore 50+ cutting-edge international art installations spread across historic waterfront warehouses in Fort Kochi.',
                'banner_image_url': 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Aspinwall House & Seafront Warehouses',
                'city': 'Kochi',
                'days_ahead': 40,
                'is_featured': True,
                'tickets': [{'name': 'Biennale Entry Pass', 'price': Decimal('499.00'), 'total_quantity': 400}],
            },
            {
                'title': 'International Film & Independent Cinema Showcase',
                'slug': 'international-film-independent-cinema-showcase',
                'short_description': 'Screening Cannes, Sundance and indie award-winners with director Q&A panel sessions.',
                'description': 'Over 30 feature films and documentaries screened across 3 state-of-the-art 4K Dolby Atmos auditoriums.',
                'banner_image_url': 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Kala Academy Main Cinema Complex',
                'city': 'Goa',
                'days_ahead': 35,
                'is_featured': False,
                'tickets': [{'name': 'Festival Cinephile Pass', 'price': Decimal('1199.00'), 'total_quantity': 250}],
            },
            {
                'title': 'Theatre & Shakespearean Drama Festival: Othello Live',
                'slug': 'theatre-shakespearean-drama-othello-live',
                'short_description': 'Electrifying stage acting, dramatic lighting, and powerful monologues by seasoned theatre actors.',
                'description': 'Experience Shakespeare classical tragedies adapted with modern Indian stagecraft and gripping acoustic scores.',
                'banner_image_url': 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Prithvi Theatre',
                'city': 'Mumbai',
                'days_ahead': 18,
                'is_featured': False,
                'tickets': [{'name': 'Front Rows Pass', 'price': Decimal('899.00'), 'total_quantity': 180}],
            },
            {
                'title': 'Heritage Handloom, Silk & Textile Master Expo',
                'slug': 'heritage-handloom-silk-textile-expo',
                'short_description': 'Banarasi brocades, Kanjivaram silks, Pashmina weaves, and master weaver live looms.',
                'description': 'Direct from artisan weaver cooperatives celebrating 5,000 years of indigenous textile craftsmanship.',
                'banner_image_url': 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Dilli Haat INA Exhibition Arena',
                'city': 'New Delhi',
                'days_ahead': 25,
                'is_featured': False,
                'tickets': [{'name': 'Visitor Pass', 'price': Decimal('299.00'), 'total_quantity': 500}],
            },
            {
                'title': 'Poetry Slam, Spoken Word & Urdu Shayari Mehfil',
                'slug': 'poetry-slam-spoken-word-shayari-mehfil',
                'short_description': 'Soul-stirring nazms, contemporary spoken word poetry, and live acoustic sarangi accompaniment.',
                'description': 'An intimate candlelit gathering where poets weave emotions through verses of love, revolution, and longing.',
                'banner_image_url': 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'The Cuckoo Club Bandra',
                'city': 'Mumbai',
                'days_ahead': 13,
                'is_featured': False,
                'tickets': [{'name': 'Mehfil Entry', 'price': Decimal('499.00'), 'total_quantity': 120}],
            },
            {
                'title': 'Ceramic Pottery & Clay Sculpture Exhibition',
                'slug': 'ceramic-pottery-clay-sculpture-exhibition',
                'short_description': 'Glazed terracotta vases, wood-fired stoneware, wheel throwing demos, and studio ceramics.',
                'description': 'Studio potters and clay sculptors display bespoke ceramic functional wares and artistic sculptures.',
                'banner_image_url': 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': '1 Shanthi Road Studio Gallery',
                'city': 'Bengaluru',
                'days_ahead': 19,
                'is_featured': False,
                'tickets': [{'name': 'Gallery Pass', 'price': Decimal('349.00'), 'total_quantity': 150}],
            },
            {
                'title': 'Folk Music, Baul Songs & Tribal Heritage Carnival',
                'slug': 'folk-music-baul-tribal-heritage-carnival',
                'short_description': 'Ektara melodies, Rajasthani Manganiyar choruses, and energetic tribal drum circles.',
                'description': 'Feel the raw pulse of Indian grassroots music under open skies with authentic artisan craft stalls.',
                'banner_image_url': 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Shantiniketan Open Mela Grounds',
                'city': 'Bolpur',
                'days_ahead': 36,
                'is_featured': False,
                'tickets': [{'name': 'Mela Pass', 'price': Decimal('399.00'), 'total_quantity': 350}],
            },
            {
                'title': 'Ancient Heritage Monuments & Temple Architecture Walk',
                'slug': 'ancient-monuments-temple-architecture-walk',
                'short_description': 'Guided walking tour uncovering the stone marvels and monolithic carvings of Hampi.',
                'description': 'Led by veteran archaeologists and historians tracing the architectural genius of the Vijayanagara Empire.',
                'banner_image_url': 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Virupaksha Temple Plaza',
                'city': 'Hampi',
                'days_ahead': 27,
                'is_featured': False,
                'tickets': [{'name': 'Archaeology Guided Tour', 'price': Decimal('899.00'), 'total_quantity': 60}],
            },
            {
                'title': 'Traditional Marionette & Shadow Puppetry Festival',
                'slug': 'traditional-marionette-shadow-puppetry-festival',
                'short_description': 'Kathputli string puppets, Togalu Gombeyaata shadow plays, and puppet making workshops.',
                'description': 'Generational puppeteers bring ancient mythological epics to life behind illuminated translucent cotton screens.',
                'banner_image_url': 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Sangeet Natak Akademi Auditorium',
                'city': 'New Delhi',
                'days_ahead': 32,
                'is_featured': False,
                'tickets': [{'name': 'Family Pass (Admit 2)', 'price': Decimal('599.00'), 'total_quantity': 180}],
            },
            {
                'title': 'Origami, Paper Craft & Japanese Zen Arts Workshop',
                'slug': 'origami-paper-craft-japanese-zen-arts',
                'short_description': 'Master intricate 3D modular origami cranes, dragons, washi paper folding, and Zen calligraphy.',
                'description': 'An atelier taught by certified origami masters with authentic imported Chiyogami patterned papers.',
                'banner_image_url': 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Japan Foundation Gallery',
                'city': 'New Delhi',
                'days_ahead': 17,
                'is_featured': False,
                'tickets': [{'name': 'Origami Kit & Pass', 'price': Decimal('699.00'), 'total_quantity': 40}],
            },
            {
                'title': 'Street Theatre & Social Play Showcase (Nukkad Natak)',
                'slug': 'street-theatre-social-play-nukkad-natak',
                'short_description': 'Powerful dafli beats, energetic chorus acting, and thought-provoking social satire plays.',
                'description': 'Collegiate and professional street theatre troupes compete in an open amphitheatre with roaring crowds.',
                'banner_image_url': 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Central Park Amphitheatre Connaught Place',
                'city': 'New Delhi',
                'days_ahead': 20,
                'is_featured': False,
                'tickets': [{'name': 'Open RSVP', 'price': Decimal('0.00'), 'total_quantity': 400}],
            },
            {
                'title': 'Renaissance Oil Painting & Impasto Canvas Workshop',
                'slug': 'renaissance-oil-painting-impasto-workshop',
                'short_description': 'Chiaroscuro lighting, palette knife impasto textures, and classical oil glaze layering.',
                'description': 'Paint your own 16x20 stretched canvas masterpiece using rich artist-grade oil pigments under expert guidance.',
                'banner_image_url': 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'National Gallery of Modern Art (NGMA)',
                'city': 'Bengaluru',
                'days_ahead': 24,
                'is_featured': False,
                'tickets': [{'name': 'Complete Painting Kit & Seat', 'price': Decimal('1499.00'), 'total_quantity': 35}],
            },
            {
                'title': 'Sacred Chants, Vedic Hymns & Temple Symphony Night',
                'slug': 'sacred-chants-vedic-hymns-temple-symphony',
                'short_description': 'Harmonious Sanskrit chanting, sound vibrations, Tibetan singing bowls, and acoustic sitar.',
                'description': 'An uplifting spiritual sound concert fostering deep inner peace, mindfulness, and timeless cultural resonance.',
                'banner_image_url': 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=1200&auto=format&fit=crop&q=80',
                'event_type': EventType.IN_PERSON,
                'venue_name': 'Isha Yoga Center Spanda Hall',
                'city': 'Coimbatore',
                'days_ahead': 45,
                'is_featured': False,
                'tickets': [{'name': 'Spanda Hall Pass', 'price': Decimal('599.00'), 'total_quantity': 300}],
            },
        ]

        all_additional = [
            (cat_conf, org_conf, conf_events),
            (cat_food, org_food, food_events),
            (cat_net, org_net, net_events),
            (cat_arts, org_arts, arts_events),
        ]

        total_added = 0
        for category, organizer, events_list in all_additional:
            self.stdout.write(f"\nProcessing Category: {category.name} ({len(events_list)} events)...")
            for item in events_list:
                slug = item['slug']
                tickets_data = item.get('tickets', [])
                days_ahead = item.get('days_ahead', 14)
                
                event_date = timezone.now().date() + timedelta(days=days_ahead)

                event, _ = Event.objects.update_or_create(
                    slug=slug,
                    defaults={
                        'title': item['title'],
                        'category': category,
                        'organizer': organizer,
                        'short_description': item['short_description'],
                        'description': item['description'],
                        'banner_image_url': item['banner_image_url'],
                        'event_type': item.get('event_type', EventType.IN_PERSON),
                        'venue_name': item.get('venue_name', 'Main Convention Arena'),
                        'address': item.get('address', 'Downtown City Center'),
                        'city': item.get('city', 'Bengaluru'),
                        'country': 'India',
                        'start_date': event_date,
                        'end_date': event_date,
                        'start_time': time(10, 0),
                        'end_time': time(18, 0),
                        'status': EventStatus.PUBLISHED,
                        'is_featured': item.get('is_featured', False),
                        'is_trending': False,
                        'contact_email': organizer.email,
                        'contact_phone': '+91 98765 00000',
                    }
                )

                event.ticket_types.all().delete()
                for idx, t_info in enumerate(tickets_data):
                    tot_qty = t_info.get('total_quantity', 100)
                    avail_qty = max(1, int(tot_qty * 0.75))
                    TicketType.objects.create(
                        event=event,
                        name=t_info['name'],
                        price=t_info['price'],
                        total_quantity=tot_qty,
                        available_quantity=avail_qty,
                        order=idx
                    )

                if not event.speakers.exists():
                    Speaker.objects.create(
                        event=event,
                        name=f"Curator ({category.name})",
                        designation="Keynote Speaker & Domain Expert",
                        company=organizer.organization_name,
                        bio="Leading veteran with over a decade of domain expertise.",
                        avatar_url=organizer.avatar_url
                    )

                total_added += 1

        self.stdout.write(self.style.SUCCESS(f"\nSuccessfully seeded {total_added} additional events!"))
