# Generated by Django 6.1 on 2026-08-08 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('attendee_name', models.CharField(max_length=150)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('seat_label', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/')),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking')),
                ('booking_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bookings.bookingitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
